### ISSUE TITLE
Can't log in even after manually solving captcha

### ISSUE THREAD

**Issue by MaximumPotato** [Revadike/node-epicgames-client-login-adapter#7]
Run npm start, the script asks me to attempt to solve the captcha manually, and then I see this:

![image](https://user-images.githubusercontent.com/11758719/113349343-41575600-930e-11eb-8f63-952d5806392b.png)

Here's the corresponding run in the console:

> C:\Users\Core\epicgames-freebies-claimer>npm start
> 
> > epicgames-freebies-claimer@1.4.1 start
> > node claimer.js
> 
>  2021-04-01 | 17:16:41.202 | WARN  | Invalid captcha!
>  2021-04-01 | 17:16:41.204 | WARN  | Failed to login as xyz@gmail.com, please attempt manually.
>  2021-04-01 | 17:17:21.824 | ERROR | TimeoutError: waiting for selector "#login:not(:disabled)" failed: timeout 30000ms exceeded
>     at new WaitTask (C:\Users\Core\epicgames-freebies-claimer\node_modules\puppeteer\lib\DOMWorld.js:549:28)
>     at DOMWorld._waitForSelectorOrXPath (C:\Users\Core\epicgames-freebies-claimer\node_modules\puppeteer\lib\DOMWorld.js:478:22)
>     at DOMWorld.waitForSelector (C:\Users\Core\epicgames-freebies-claimer\node_modules\puppeteer\lib\DOMWorld.js:432:17)
>     at Frame.waitForSelector (C:\Users\Core\epicgames-freebies-claimer\node_modules\puppeteer\lib\FrameManager.js:627:47)
>     at Frame.<anonymous> (C:\Users\Core\epicgames-freebies-claimer\node_modules\puppeteer\lib\helper.js:112:23)
>     at Page.waitForSelector (C:\Users\Core\epicgames-freebies-claimer\node_modules\puppeteer\lib\Page.js:1122:29)
>     at Function.authenticate (C:\Users\Core\epicgames-freebies-claimer\node_modules\epicgames-client-login-adapter\index.js:119:38)
>     at processTicksAndRejections (node:internal/process/task_queues:94:5)
>     at async Function.init (C:\Users\Core\epicgames-freebies-claimer\node_modules\epicgames-client-login-adapter\index.js:204:7)
>     at async C:\Users\Core\epicgames-freebies-claimer\claimer.js:110:28
> npm ERR! code 1
> npm ERR! path C:\Users\Core\epicgames-freebies-claimer
> npm ERR! command failed
> npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node claimer.js
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\ProgramData\npm\npm-cache\_logs\2021-04-01T20_17_21_934Z-debug.log

**Comment by MaximumPotato** [comment]
@Revadike Good timing on the issue move, the other repo got nuked.

I was just looking for a ticket I had opened and solved over there so I don't have to work thru this other problem again. :~)
